### ISSUE TITLE
Runner should not have flaky test / race condition.

### ISSUE THREAD

**Issue by boojamya** [strangelove-ventures/interchaintest#300] opened 2022-09-21 23:05 UTC
![Screen Shot 2022-09-21 at 4 03 20 PM](https://user-images.githubusercontent.com/56059752/191625327-26891a1d-0cb8-450b-bc59-9e56ff7b2372.png)

![Screen Shot 2022-09-21 at 4 04 16 PM](https://user-images.githubusercontent.com/56059752/191625337-492c21e5-f7ca-485d-a517-98805065fbe7.png)

**Comment by DavidNix** [comment] 2022-09-23 17:07
Relates to https://github.com/strangelove-ventures/ibctest/pull/302

The sqlitedb hasn't been tuned or was initially designed for a high number of concurrent writers. We think the migrations on the same db file may be the root cause.

**Comment by agouin** [comment] 2022-09-25 16:49
`failed to track blocks: migrate sqlite database /home/strangelove/.ibctest/databases/block.db; deleting file recommended: upsert schema_version with git sha unknown: database is locked (5) (SQLITE_BUSY)`

https://github.com/strangelove-ventures/ibctest/actions/runs/3121482563/jobs/5065142331

**Comment by agouin** [comment] 2022-12-01 18:55
https://github.com/strangelove-ventures/ibctest/actions/runs/3595140069/jobs/6054262944

race detected around sqlite

**Comment by Reecepbcups** [comment] 2023-11-26 20:38
race conditions have been resolved with the change in actions now. Future issues can be solved on a case by case basis now

**Closed by Reecepbcups** 2023-11-26 20:38 UTC
Labels: bug
